language: python
jdk: openjdk8
dist: xenial
sudo: required
cache:
  pip: true
python:
  - "3.8"
before_install:
  - mkdir -p /opt
  - wget https://dlcdn.apache.org/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
  - tar xvf spark-3.1.2-bin-hadoop3.2.tgz
  - sudo mv spark-3.1.2-bin-hadoop3.2 /opt
  - rm spark-3.1.2-bin-hadoop3.2.tgz
  - export SPARK_HOME=/opt/spark-3.1.2-bin-hadoop3.2
  - export PATH=$PATH:/opt/spark-3.1.2-bin-hadoop3.2/bin
install:
  - pip install -r requirements.txt
script:
  - cd test/
  - python -m unittest discover